# Generated by Django 3.2.6 on 2022-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='LJ7NFVHG4VBPSMY', max_length=20),
        ),
    ]
