# Generated by Django 3.2.6 on 2022-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20220210_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product', to='Product.Image'),
        ),
    ]
