# Generated by Django 3.2.6 on 2022-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220211_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status_show',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10),
        ),
    ]
