# Generated by Django 3.2.6 on 2022-02-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_status_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
