# Generated by Django 3.2.6 on 2022-02-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_color_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='count',
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Product.product')),
            ],
        ),
    ]
