# Generated by Django 3.2.6 on 2022-02-13 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20220214_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
