# Generated by Django 3.2.6 on 2022-02-14 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_auto_20220214_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Product.color'),
        ),
    ]
