# Generated by Django 3.2.6 on 2022-02-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_productstock_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
    ]
