# Generated by Django 3.2.6 on 2022-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_remove_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
