# Generated by Django 3.2.6 on 2022-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_auto_20220215_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
