# Generated by Django 3.2.6 on 2022-02-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_typeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.typeproduct'),
            preserve_default=False,
        ),
    ]
