# Generated by Django 3.2.6 on 2022-02-18 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transportation', '0002_shipping_price'),
        ('Product', '0030_alter_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeText', models.CharField(max_length=50, null=True)),
                ('colorText', models.CharField(max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
                ('productStock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.productstock')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeCreate', models.DateTimeField(auto_now_add=True)),
                ('shippingText', models.CharField(max_length=50, null=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('details', models.ManyToManyField(to='Product.OrderDetail')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transportation.shipping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
