# Generated by Django 3.2.6 on 2022-02-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_auto_20220219_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.order'),
            preserve_default=False,
        ),
    ]
