# Generated by Django 3.2.6 on 2022-02-19 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_auto_20220219_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='awa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='dateTimeCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='awda', max_length=200),
            preserve_default=False,
        ),
    ]
