# Generated by Django 3.2.6 on 2022-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_auto_20220219_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=12),
            preserve_default=False,
        ),
    ]
