# Generated by Django 3.2.6 on 2022-02-19 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_coupon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateTimePay',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
