# Generated by Django 3.2.6 on 2022-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0037_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateTimePay',
            field=models.DateTimeField(null=True),
        ),
    ]
