# Generated by Django 3.2.6 on 2022-02-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_alter_order_datetimepay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
