# Generated by Django 3.2.6 on 2022-02-21 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0003_auto_20220221_0317'),
        ('Product', '0039_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transportation.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='addressText',
            field=models.TextField(null=True),
        ),
    ]
