# Generated by Django 3.2.6 on 2022-02-22 01:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_mission', models.TextField()),
                ('our_vision', models.TextField()),
                ('who_we_are', ckeditor.fields.RichTextField()),
                ('token_blog', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
