# Generated by Django 3.2.6 on 2022-02-22 02:58

import Public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutStor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('store_hour', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=Public.models.upload_src_image_out_stor)),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='address_office',
            field=models.CharField(default='awd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(default='info@molla.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone_number',
            field=models.CharField(default=1324, max_length=20),
            preserve_default=False,
        ),
    ]
