# Generated by Django 3.2.6 on 2022-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_auto_20220222_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
