# Generated by Django 3.2.6 on 2022-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0003_commentsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstor',
            name='phone_number',
            field=models.CharField(default='awd', max_length=20),
            preserve_default=False,
        ),
    ]
