# Generated by Django 3.2.6 on 2022-02-22 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0006_siteinfo_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsupport',
            name='dateTimeSubmit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
