# Generated by Django 3.2.6 on 2022-03-05 05:51

import Config.Tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyBlog',
            field=models.CharField(default=Config.Tools.RandomString, max_length=50),
        ),
    ]
