# Generated by Django 3.2.6 on 2022-03-05 06:00

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_user_keyblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyBlog',
            field=models.CharField(default=User.models.RandomString, max_length=50),
        ),
    ]
